// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./asana-links.js')
  await import('./signature.js')
  await import('./config.js')
  await import('./asana.js')
  await import('./pull_request.js')
  await import('./http-server.js')

  test.resume()
}
